"""finishes setup for Card and Board models

Revision ID: 5e758aa62e08
Revises: abe2424673e5
Create Date: 2023-06-26 11:24:00.315724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e758aa62e08'
down_revision = 'abe2424673e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('card_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('card', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('card', 'card_id')
    # ### end Alembic commands ###
